In [1]:
import os
os.chdir('E:\Documents\Fajar Docs\Latihan Python')

In [2]:
import pandas as pd
data=pd.read_csv('dt2.csv')

In [3]:
data

      Y   X    Z
0   5.0  21  2.4
1   4.8  20  2.4
2   4.5  16  2.4
3   4.8  18  2.5
4   4.5  16  3.2
5   3.9  18  3.1
6   3.2  12  3.2
7   3.3  12  2.7
8   4.6  13  2.7
9   4.9  13  2.7
10  4.0  17  2.7
11  3.6  24  2.8
12  5.2  11  2.5
13  3.8  10  2.6
14  4.9  17  2.0
15  4.1  14  2.0
16  5.1  14  2.1
17  4.3  20  2.1
18  4.9  12  1.9
19  4.6  11  2.0